apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-ordering-deployment
  labels:
    app: pizza-ordering
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza-ordering
  template:
    metadata:
      labels:
        app: pizza-ordering
    spec:
      containers:
      - name: pizza-ordering
        image: pizza-ordering:0.0.1
        ports:
        - containerPort: 9000