apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-ordering-deployment-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-ordering-web
  template:
    metadata:
      labels:
        app: pizza-ordering-web
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
            - key: config
              path: default.conf