apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-ordering-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pizza-ordering
  template:
    metadata:
      labels:
        app: pizza-ordering
    spec:
      containers:
      - name: pizza-ordering
        image: pizza-ordering:0.0.2
        ports:
        - containerPort: 9000
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d
      
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
            - key: config
              path: default.conf