apiVersion: v1
kind: Service
metadata:
  name: pizza-ordering-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 80
  selector:
    app: pizza-ordering